##########################################################################
####   This file contains the script to create jar files from src   ######
####   folder and store them in ext folder.                         ######
##########################################################################